---
- hosts: nodes
  name: OpenShift Node Instances Configuration

  tasks:
  
  - name: insert a line in /etc/hosts for master if needed
    lineinfile:
      dest: /etc/hosts
      regexp: "^10.0.0.30"
      line: "10.0.0.30 master console master0.example.com console.example.com"

  - name: insert a line in /etc/hosts for node-01 if needed
    lineinfile:
      dest: /etc/hosts
      regexp: "^10.0.0.40"
      line: "10.0.0.40 node0 node0.example.com"

  - name: epel-release
    yum:
     name: epel-release
     state: present

  - name: disable repo epel
    replace:
     path: "/etc/yum.repos.d/epel.repo"
     regexp: "^enabled=1"
     replace: "enabled=0"

  - name: Install Packages
    yum:
      enablerepo: epel
      name: "{{ item }}"
      state: latest
    with_items:
      - wget
      - git
      - zile
      - vim
      - net-tools
      - docker-1.13.1
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - openssl-devel
      - httpd-tools
      - NetworkManager
      - python-cryptography
      - python2-pip
      - python-devel
      - python-passlib
      - java-1.8.0-openjdk-headless
      - "@Development Tools"

  - name: enable NetworkManager
    systemd:
      name: NetworkManager
      state: started
      enabled: yes

  - name: install pyOpenSSL
    yum:
      enablerepo: epel
      name: "{{ item }}"
      state: latest
    with_items:
      - pyOpenSSL
  
  - name: disable firewall
    systemd:
      name: firewalld
      state: stopped
      enabled: no
  
  - name: restart Docker service
    systemd:
      name: docker
      state: restarted
      enabled: yes

